FROM registry.suse.com/bci/golang:1.25 AS builder
ENV GOTOOLCHAIN=auto
WORKDIR /app
COPY --chown=1001:0 ./ ./
RUN go build -buildvcs=false -ldflags="-w -s" github.com/kubev2v/forklift/cmd/openstack-populator

FROM registry.suse.com/bci/bci-base:15.7
# Required to be able to get files from within the pod

RUN zypper -n rm container-suseconnect && \
    zypper -n install tar && \
    zypper -n clean -a

COPY --from=builder /app/openstack-populator /usr/local/bin/openstack-populator
ENTRYPOINT ["/usr/local/bin/openstack-populator"]